cmake_minimum_required(VERSION 3.18)
if (NOT TARGET PluginUserComponent)
    get_filename_component(bin_path "${CMAKE_CURRENT_LIST_DIR}/../bin/" ABSOLUTE)
    add_library(PluginUserComponent SHARED IMPORTED GLOBAL)
    if (${CMAKE_SYSTEM_NAME} STREQUAL "Android")
        set_property(TARGET PluginUserComponent PROPERTY IMPORTED_LOCATION "${bin_path}/android/${CMAKE_ANDROID_ARCH_ABI}/libPluginUserComponent.so")
    elseif (${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
        set_property(TARGET PluginUserComponent PROPERTY IMPORTED_LOCATION "${bin_path}/windows/x64/PluginUserComponent.dll")
    else()
        message(FATAL_ERROR "Unknown system ${CMAKE_SYSTEM_NAME}")
    endif()
endif()
