export class Constants{
  /*
  BOOK_BOX_WIDTH
   */
  static readonly BOOK_BOX_WIDTH = 300;
  /*
  BOOK_BOX_HEIGHT
   */
  static readonly BOOK_BOX_HEIGHT = 68;
  /*
  BOOK_ITEM_WIDTH
   */
  static readonly BOOK_ITEM_WIDTH = this.BOOK_BOX_WIDTH * 0.04;
  /*
  BOOK_ITEM_SPACE
   */
  static readonly BOOK_ITEM_SPACE = this.BOOK_BOX_WIDTH * 0.005;
  /*
  BOOK_WIDTH
   */
  static readonly BOOK_WIDTH = this.BOOK_BOX_WIDTH * 0.04;
  /*
  BOOK_LENGTH
   */
  static readonly BOOK_LENGTH = this.BOOK_BOX_WIDTH * 0.10;

  /*
  round constants
   */
  static  readonly ROUND_R = 20

  static readonly ROUND_R_OUTER = 30

  static readonly MATE_60_PRO_WIDTH = 1260;

  static readonly MATE_60_PRO_HEIGHT = 2720;

  static readonly CONTROL_STEP = 5
}
